dist: xenial
sudo: required
language: java

env:
  global:
  - SONATYPE_USERNAME=ph@phloc.com
  - secure: "NAUmmXrYtF6RtuAY500xrAqlqiDZ/e+h+3vNjMtJes6X8VyzIPQ3ibmWLgc1Tqi9f+rO4S1fuypEh1JrlAZfYM1nwWt6xH2p3ffaBXa7ewTaAqwXikXbJyMR2TSM+N/2XLWZqSJ5PIN11BYUzU8/qsBqqP0pxm3t8mgI/vy/aoHnPeLq5qMLP
cuukXwzpLMEv+L290fGi536ctou88xFO2zkwRZuATR4aJYz8/G+fvE18rpASWq9p2Z/KUrGMyvzYXjmzMKPhcmBCg7A9U9r7GRM6zZ7UefZb/NUCIdcPSq+U61bC3N4V8w9dvAwybeWJL5K6/5ZnV9C1WwPCncfn1nJO1FNFXFdnIXNi6AFx2slJo04KczlO
GIAiN8ECJutNd23aljn8VaC4aYOtVw/4EIGr6DNccmsu3bUlM1ARZLDcxp2B60Sv1xgvCkef5UvkW4eUxCztMEx0egtGwFsWkxOmgyRsXoZ5ifolujZFlp6dG8th7Rw3uQ+BdGXxjNz5b2ub4oGI1sVcvMHnjrCw+E01Wwf+Vjh9GwI82Nro9hgZYLusdFeL
1SuGx+aHulkQQfj9qzDla0ULmBJ1LaHC+LpCb2KXJyDWHFfuj1oh+yJV8MLVAExpYmlIEBCVAZNsAv8lU8eZsqBWwk+r1NEDLWGQUiTTaJ1ZE2ZDwZHKlA="

addons:
  sonarcloud:
    organization: toop4eu
    token:
      secure: "opxeduVELfRmE6Q12ACpEwFv2SLX1vS/b+3yoXLluSz7M73E+KupGHcls327WTT73luuCuNjjX/hlqwd9myIbvFYNWcEla+TnKwZ6Fu5nsjkiqieCFABeITOSsXjC4c
2B+RsFjcSEihzdVAMW1LGiDm/82vY7B97XJqdr7mLfo1+gtmUXVaBgyeAgLzdHzosiCDaBd7qMzCWLcOch7kCJTehDdtwllYaljYx0RkKebW7Pz3AW4rB5Tbsi8vUdAsB3CjXoWTO+
0VitzjSX1dbX4C0AP+jAQeBacuox+F/GFr3RbeWczG6k/R5Fjb82RArqoMFfu/DAOyVLj3UeOL/UruOK0J0vyYVPOQQ0gWqk84UkNSI83ApTIngBhqG9YwN5KvVy8flcQKmJ5tmGXm
xuTK9k8ajKVTkT5WMOqiXzI1cpwGy36KHjGAcspeAY6GSK91qVchoK1BGLGwyAuJ9tWuta8zKM0qLW8uWUsm5VCEPFd/3kfnJkgwqEVRJYvoplvqYGUKQewjsVfhqtJ2GwJzhPaBBN
WWZPzxxuE5m6NXqGyk7M99se0VQO/bFnDyjHraCfkUGnW6lDpY/FU1f0BhWWI5NlhNgZkLMpN8nybtxr1vprr0jYrHEyHxZj5NTdjmfmDILSs+XSLC3CTshBjZT9E7yirUY/7mDy38
n62I="

install:
- mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -U

cache:
  directories:
  - "$HOME/.m2"

branches:
  only:
  - master

jobs:
  include:
  - stage: test
    jdk: openjdk8
    script:
    - mvn test -B -P coverage sonar:sonar
    after_success:
    - mvn deploy --settings travis-settings.xml -DskipTests=true -B -P travis-deploy
    - bash <(curl -s https://codecov.io/bash)
  - stage: test
    jdk: openjdk11
    script:
    - mvn test -B
  - stage: test
    jdk: openjdk14
    script:
    - mvn test -B
